// <auto-generated />
namespace BlogASP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Datamigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Datamigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201810021726431_Data-migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
